[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-steputils"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
